// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snake.BackEnd;

namespace Snake.BackEnd.Migrations
{
    [DbContext(typeof(SnakeDBContext))]
    [Migration("20200918064714_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Snake.BackEnd.Models.Apple", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplePositionX")
                        .HasColumnType("int");

                    b.Property<int>("ApplePositionY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Apple");
                });

            modelBuilder.Entity("Snake.BackEnd.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SnakeLength")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Snake.BackEnd.Models.Snake", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SnakeBodyPositionX")
                        .HasColumnType("int");

                    b.Property<int>("SnakeBodyPositionY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Snake");
                });
#pragma warning restore 612, 618
        }
    }
}
